welcomeUI <- function(id) {
  
  ns <- NS(id)
  
  fluidPage(

    fluidRow(
      column(6,
        h3("About this tool"),
        p("The Gene Explorer is actively developed and maintained by the HDRF Data Center.",
          "The goal of this tool is to facilitate data comparisons across the various HDRF labs.",
          "The tool has the results of differential gene expression analyses, from the various HDRF labs.",
          "Currently we have data on 10 such experiments across six animal models and are adding more.",
          "These experiments are described in the Animal Models page accessible from the side menu."),
        p("Currently, the sheer volume of data generated by sequencing experiments is overwhelming.",
          "Even if we limit our focus to animal models of mood disorders, the number of interventions across different brain regions is impossible to keep track of.",
          "The HDRF Gene Explorer was developed as a way of overcoming this helplessness in the face of large data.",
          "The primary aim of this tool is to facilitate comparisons across different animal models in order to find points of convergence and divergence at the gene and pathway level."),
        br(),
        h4("Future Directions"),
        p("This tool in under active development and is being updated regularly. Some of our future work will be directed towards the following:"),
        tags$ul(
          tags$li("Allow users to upload their own data"),
          tags$li("Automatic data import from GEO"),
          tags$li("Add human data"),
          tags$li("Link to single cell data")
        ),
        br(),
        h4("Contact us"),
        p("Feel free to contact us with any suggestions, any bugs you enounter, or just to say hi!",
          "This tool is currently developed and maintained by ", a("Huzefa Khalil", href = "mailto:huzefa@med.umich.edu"), "."),
        p("The tool was presented at the HDRF retreat in 2022 which was held in Ann Arbor.",
          "The slides from that presentation are accessible ",
          a("here", href = "https://docs.google.com/presentation/d/12o3RD5NNMdx1igvh3ekkaYlAOn_ZwNqf/edit?usp=sharing&ouid=115122258211291370510&rtpof=true&sd=true"),
          ".")
      )
    )
    
  )
}